# Private options --------------------------------------------------------------

# Add your real Reddit username here.
userAgent: A bot by /u/<your real Reddit username goes here>
# The username for the bot.
username: username
# Its password.
password: password
# Get one from: http://api.imgur.com/oauth2/addclient
imgurClientId: id

# Other options ----------------------------------------------------------------

# How many seconds to wait between coments
pauseTime: 600
# The minimum number of comments a submission has to have.
minComments: 200
# The maximum number of words to be included.
maxWords: 22
# The template for the comment.
commentFormat: ^[Woof.]({imageUrl})

# The name of the font used by the Cairo library.
fontName: Comic Sans MS
# The path to the font used by the PIL library.
# This example works under Ubuntu.
fontPath: /usr/share/fonts/truetype/msttcorefonts/Comic_Sans_MS.ttf
# The initial font is the largest size used. The number is expressed as a ratio
# of the height.
initialFontSize: 0.045
# Font stroke width as ratio of font size.
fontStroke: 0.02
